### ISSUE TITLE
does this work?

### ISSUE THREAD

**Issue by BrandonCopley** [kevingibbon/IMAPClient#1]
Does this work?

I keep getting that I can't connect to gmail when I try to use this.

**Comment by bcoe** [comment]
Could you paste the code that you're using to connect. It's been a while since I've done any development on this library, but it was left in a working state.

**Comment by chrhansen** [comment]
Looks nice, clean and simple. But can't build a project. I've added the imap.h/m and the static library libIMAP.a created in the example project to template single-view iOS application but I get: 
`Undefined symbols for architecture armv7s:
  "_kCFStreamSSLPeerName", referenced from:
      -[IMAP open] in imap.o
  "_kCFStreamSSLValidatesCertificateChain", referenced from:
      -[IMAP open] in imap.o
  "_kCFStreamSSLAllowsExpiredCertificates", referenced from:
      -[IMAP open] in imap.o
  "_kCFStreamSSLAllowsAnyRoot", referenced from:
      -[IMAP open] in imap.o
  "_kCFStreamPropertySSLSettings", referenced from:
      -[IMAP open] in imap.o`
Even though armv7s are one of the build architectures in the sample project.
Could your provide a full sample project, or even better a step-by-step how to integrate into an existing project.

Thanks.

**Comment by harish020102** [comment]
Just Add CFNetwork.framework from Build Phases all above errors will be solved

**Comment by BrandonCopley** [comment]
This is an outdated issue, I have no idea if it works or not. If someone else has issues they can reopen it.
